import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import { Footer } from './footer/footer'
import './globals.css'

const geistSans = Poppins({ weight: '500', subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-br" className="h-full">
      <body
        className={`${geistSans} antialiased max-w-[100dvw] min-h-full bg-[#710627] overflow-x-hidden relative flex flex-col`}
      >
        {children}
        <Footer />
      </body>
    </html>
  )
}
